version: 2
jobs:
  build:
    branches:
      only:
        - master #Only building for master branch pushes
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip
            unzip packer*.zip
            chmod +x packer
      - run:
          name: Validate Packer Template
          command: ./packer -var 'source_ami=${source_ami}' validate ami.json
      - run:
          name: Build AMI
          command: |
            ./packer build \
            -var 'aws_region=${aws_region}' \
            -var 'aws_access_key=${aws_access_key}' \
            -var 'aws_secret_key=${aws_secret_key}' \
            -var 'source_ami=${source_ami} \
            -var 'ami_users=${ami_users}' \
             ami.json
